
namespace :demo do
  desc "populate data for demo"
  task :populate  => :environment  do

modes = Mode.all

mi_systems = MiSystem.create([{name: 'MIS1', comment: 'Describing MIS1', api_url: 'mis1.org', api_key: 'key1', start_date: Time.now, end_date: Time.new('2030/12/31 23:59:59'), multiple_starts_and_arrivals: 1, modes: modes[0,7]},
                              {name: 'MIS2', comment: 'Describing MIS2', api_url: 'mis2.org', api_key: 'key2', start_date: Time.now, end_date: Time.new('2030/12/31 23:59:59'), multiple_starts_and_arrivals: 1, modes: modes[2,6]},
                              {name: 'MIS3', comment: 'Describing MIS3', api_url: 'mis3.org', api_key: 'key3', start_date: Time.now, end_date: Time.new('2030/12/31 23:59:59'), multiple_starts_and_arrivals: 1, modes: modes[0,7]},
                              {name: 'MIS4', comment: 'Describing MIS4', api_url: 'mis4.org', api_key: 'key4', start_date: Time.now, end_date: Time.new('2030/12/31 23:59:59'), multiple_starts_and_arrivals: 1, modes: modes[2,2]},
                              {name: 'MIS5', comment: 'Describing MIS5', api_url: 'mis5.org', api_key: 'key5', start_date: Time.now, end_date: Time.new('2030/12/31 23:59:59'), multiple_starts_and_arrivals: 1, modes: modes[3,5]}])

stops = Stop.create([{stop_code: 1, mi_system_id: mi_systems[0].id, name: 'STOP 1 OF MIS 1', stop_type: 0, administrative_code: 'code 1 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5656, 48.0909) },
                     {stop_code: 2, mi_system_id: mi_systems[0].id, name: 'STOP 2 OF MIS 1', stop_type: 0, administrative_code: 'code 1 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5657, 48.0909) },
                     {stop_code: 3, mi_system_id: mi_systems[0].id, name: 'STOP 3 OF MIS 1', stop_type: 0, administrative_code: 'code 1 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5658, 48.0909) },
                     {stop_code: 4, mi_system_id: mi_systems[0].id, name: 'STOP 4 OF MIS 1', stop_type: 0, administrative_code: 'code 1 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5659, 48.0909) },
                     {stop_code: 5, mi_system_id: mi_systems[0].id, name: 'STOP 5 OF MIS 1', stop_type: 0, administrative_code: 'code 1 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5660, 48.0909) },
                     {stop_code: 6, mi_system_id: mi_systems[0].id, name: 'STOP 6 OF MIS 1', stop_type: 0, administrative_code: 'code 2 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5661, 48.0909) },
                     {stop_code: 7, mi_system_id: mi_systems[0].id, name: 'STOP 7 OF MIS 1', stop_type: 0, administrative_code: 'code 2 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5662, 48.0909) },
                     {stop_code: 8, mi_system_id: mi_systems[0].id, name: 'STOP 8 OF MIS 1', stop_type: 0, administrative_code: 'code 2 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5663, 48.0909) },
                     {stop_code: 9, mi_system_id: mi_systems[0].id, name: 'STOP 9 OF MIS 1', stop_type: 0, administrative_code: 'code 2 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5664, 48.0909) },
                     {stop_code: 10, mi_system_id: mi_systems[0].id, name: 'STOP 10 OF MIS 1', stop_type: 0, administrative_code: 'code 2 1', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5665, 48.0909) },
                     {stop_code: 1, mi_system_id: mi_systems[1].id, name: 'STOP 1 OF MIS 2', stop_type: 0, administrative_code: 'code 1 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5666, 48.0909) },
                     {stop_code: 2, mi_system_id: mi_systems[1].id, name: 'STOP 2 OF MIS 2', stop_type: 0, administrative_code: 'code 1 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5667, 48.0909) },
                     {stop_code: 3, mi_system_id: mi_systems[1].id, name: 'STOP 3 OF MIS 2', stop_type: 0, administrative_code: 'code 1 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5668, 48.0909) },
                     {stop_code: 4, mi_system_id: mi_systems[1].id, name: 'STOP 4 OF MIS 2', stop_type: 0, administrative_code: 'code 1 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5669, 48.0909) },
                     {stop_code: 5, mi_system_id: mi_systems[1].id, name: 'STOP 5 OF MIS 2', stop_type: 0, administrative_code: 'code 1 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5670, 48.0909) },
                     {stop_code: 6, mi_system_id: mi_systems[1].id, name: 'STOP 6 OF MIS 2', stop_type: 0, administrative_code: 'code 2 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5671, 48.0909) },
                     {stop_code: 7, mi_system_id: mi_systems[1].id, name: 'STOP 7 OF MIS 2', stop_type: 0, administrative_code: 'code 2 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5672, 48.0909) },
                     {stop_code: 8, mi_system_id: mi_systems[1].id, name: 'STOP 8 OF MIS 2', stop_type: 0, administrative_code: 'code 2 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5673, 48.0909) },
                     {stop_code: 9, mi_system_id: mi_systems[1].id, name: 'STOP 9 OF MIS 2', stop_type: 0, administrative_code: 'code 2 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5674, 48.0909) },
                     {stop_code: 10, mi_system_id: mi_systems[1].id, name: 'STOP 10 OF MIS 2', stop_type: 0, administrative_code: 'code 2 2', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5675, 48.0909) },
                     {stop_code: 1, mi_system_id: mi_systems[2].id, name: 'STOP 1 OF MIS 3', stop_type: 0, administrative_code: 'code 1 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5676, 48.0909) },
                     {stop_code: 2, mi_system_id: mi_systems[2].id, name: 'STOP 2 OF MIS 3', stop_type: 0, administrative_code: 'code 1 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5677, 48.0909) },
                     {stop_code: 3, mi_system_id: mi_systems[2].id, name: 'STOP 3 OF MIS 3', stop_type: 0, administrative_code: 'code 1 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5678, 48.0909) },
                     {stop_code: 4, mi_system_id: mi_systems[2].id, name: 'STOP 4 OF MIS 3', stop_type: 0, administrative_code: 'code 1 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5679, 48.0909) },
                     {stop_code: 5, mi_system_id: mi_systems[2].id, name: 'STOP 5 OF MIS 3', stop_type: 0, administrative_code: 'code 1 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5680, 48.0909) },
                     {stop_code: 6, mi_system_id: mi_systems[2].id, name: 'STOP 6 OF MIS 3', stop_type: 0, administrative_code: 'code 2 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5681, 48.0909) },
                     {stop_code: 7, mi_system_id: mi_systems[2].id, name: 'STOP 7 OF MIS 3', stop_type: 0, administrative_code: 'code 2 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5682, 48.0909) },
                     {stop_code: 8, mi_system_id: mi_systems[2].id, name: 'STOP 8 OF MIS 3', stop_type: 0, administrative_code: 'code 2 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5683, 48.0909) },
                     {stop_code: 9, mi_system_id: mi_systems[2].id, name: 'STOP 9 OF MIS 3', stop_type: 0, administrative_code: 'code 2 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5684, 48.0909) },
                     {stop_code: 10, mi_system_id: mi_systems[2].id, name: 'STOP 10 OF MIS 3', stop_type: 0, administrative_code: 'code 2 3', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5685, 48.0909) },
                     {stop_code: 1, mi_system_id: mi_systems[3].id, name: 'STOP 1 OF MIS 4', stop_type: 0, administrative_code: 'code 1 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5686, 48.0909) },
                     {stop_code: 2, mi_system_id: mi_systems[3].id, name: 'STOP 2 OF MIS 4', stop_type: 0, administrative_code: 'code 1 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5687, 48.0909) },
                     {stop_code: 3, mi_system_id: mi_systems[3].id, name: 'STOP 3 OF MIS 4', stop_type: 0, administrative_code: 'code 1 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5688, 48.0909) },
                     {stop_code: 4, mi_system_id: mi_systems[3].id, name: 'STOP 4 OF MIS 4', stop_type: 0, administrative_code: 'code 1 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5689, 48.0909) },
                     {stop_code: 5, mi_system_id: mi_systems[3].id, name: 'STOP 5 OF MIS 4', stop_type: 0, administrative_code: 'code 1 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5690, 48.0909) },
                     {stop_code: 6, mi_system_id: mi_systems[3].id, name: 'STOP 6 OF MIS 4', stop_type: 0, administrative_code: 'code 2 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5691, 48.0909) },
                     {stop_code: 7, mi_system_id: mi_systems[3].id, name: 'STOP 7 OF MIS 4', stop_type: 0, administrative_code: 'code 2 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5692, 48.0909) },
                     {stop_code: 8, mi_system_id: mi_systems[3].id, name: 'STOP 8 OF MIS 4', stop_type: 0, administrative_code: 'code 2 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5693, 48.0909) },
                     {stop_code: 9, mi_system_id: mi_systems[3].id, name: 'STOP 9 OF MIS 4', stop_type: 0, administrative_code: 'code 2 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5694, 48.0909) },
                     {stop_code: 10, mi_system_id: mi_systems[3].id, name: 'STOP 10 OF MIS 4', stop_type: 0, administrative_code: 'code 2 4', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5695, 48.0909) },
                     {stop_code: 1, mi_system_id: mi_systems[4].id, name: 'STOP 1 OF MIS 5', stop_type: 0, administrative_code: 'code 1 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5696, 48.0909) },
                     {stop_code: 2, mi_system_id: mi_systems[4].id, name: 'STOP 2 OF MIS 5', stop_type: 0, administrative_code: 'code 1 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5697, 48.0909) },
                     {stop_code: 3, mi_system_id: mi_systems[4].id, name: 'STOP 3 OF MIS 5', stop_type: 0, administrative_code: 'code 1 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5698, 48.0909) },
                     {stop_code: 4, mi_system_id: mi_systems[4].id, name: 'STOP 4 OF MIS 5', stop_type: 0, administrative_code: 'code 1 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5699, 48.0909) },
                     {stop_code: 5, mi_system_id: mi_systems[4].id, name: 'STOP 5 OF MIS 5', stop_type: 0, administrative_code: 'code 1 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5600, 48.0909) },
                     {stop_code: 6, mi_system_id: mi_systems[4].id, name: 'STOP 6 OF MIS 5', stop_type: 0, administrative_code: 'code 2 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5601, 48.0909) },
                     {stop_code: 7, mi_system_id: mi_systems[4].id, name: 'STOP 7 OF MIS 5', stop_type: 0, administrative_code: 'code 2 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5602, 48.0909) },
                     {stop_code: 8, mi_system_id: mi_systems[4].id, name: 'STOP 8 OF MIS 5', stop_type: 0, administrative_code: 'code 2 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5603, 48.0909) },
                     {stop_code: 9, mi_system_id: mi_systems[4].id, name: 'STOP 9 OF MIS 5', stop_type: 0, administrative_code: 'code 2 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5604, 48.0909) },
                     {stop_code: 10, mi_system_id: mi_systems[4].id, name: 'STOP 10 OF MIS 5', stop_type: 0, administrative_code: 'code 2 5', site_ref: 1, transport_mode: 'trans mode 1', quay_type: 'quay 1', shape: Stop.geos_factory.point(1.5605, 48.0909) }
                     ])

  end

end

