# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgis
  encoding: unicode
  schema_search_path: public
  database: afimb_db_cway_new
  pool: 5
  username: cityway
  password: c17yW4Y13
  su_username: cityway
  su_password: c17yW4Y13

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: 82.226.26.241
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgis
  encoding: unicode
  schema_search_path: public
  database: apii_sim_backoffice_test
  pool: 5
  username: apii_sim_backoffice
  password: apii_sim_backoffice
  su_username: apii_sim_backoffice
  su_password: apii_sim_backoffice
  host: localhost
  port: 5434

production:
  adapter: postgis
  encoding: unicode
  schema_search_path: public
  database: afimb_db_cway_new
  pool: 5
  username: cityway
  password: c17yW4Y13
  su_username: cityway
  su_password: c17yW4Y13
  host: 82.226.26.241
  port: 5432
